name:                good-bot
version:             0.1.0.0
github:              "travv0/good-bot"
license:             BSD3
author:              "Travis"
maintainer:          "tssund93@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/good-bot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- discord-haskell
- exceptions
- lens
- mtl
- random
- stm
- text
- time
- wreq
- yaml

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  good-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - good-bot

tests:
  good-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - good-bot
